# Generated by Django 5.2.4 on 2025-07-18 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0003_remove_habit_completed_at_alter_habit_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
